name: Auto Approve Workflows

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - name: Get list of workflows awaiting approval
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PENDING_WORKFLOWS=$(gh api \
          -H "Accept: application/vnd.github.v3+json" \
          /repos/${{ github.repository }}/actions/runs?status=waiting | jq -r '.workflow_runs[].id')

        for WORKFLOW_ID in $PENDING_WORKFLOWS; do
          echo "Approving workflow $WORKFLOW_ID"
          gh api \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/actions/runs/$WORKFLOW_ID/approve \
            -f '[]' 
        done
